## PANDAS

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

## Create Dataframe

In [3]:
## using list
df= pd.DataFrame([11,12,13], columns=["col_name"])
print(df)

   col_name
0        11
1        12
2        13

In [8]:
df1 = pd.DataFrame([True,23,"pandas"],columns=["list"])
print(df)

     list
0    True
1      23
2  pandas

In [9]:
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [13]:
## using dictinary of list
data={
    " name ":["sneha","angel","riya"],
    " age ":[16,17,18],
    "salary":[400040,290600,34829]
}
print(data)

{' name ': ['sneha', 'angel', 'riya'], ' age ': [16, 17, 18], 'salary': [400040, 290600, 34829]}

In [15]:
df=pd.DataFrame(data)
print(df)
print(type(df))

   name    age   salary
0  sneha     16  400040
1  angel     17  290600
2   riya     18   34829
<class 'pandas.core.frame.DataFrame'>

In [20]:
df.head()

   name    age   salary
0  sneha     16  400040
1  angel     17  290600
2   riya     18   34829

In [22]:
df.tail(1)

   name    age   salary
2   riya     18   34829

In [25]:
df.shape

(3, 3)

In [27]:
df.columns

Index([' name ', ' age ', 'salary'], dtype='object')

In [30]:
df.rename(columns={"salary":"Monthly salary"},inplace=True)

In [33]:
df
print(df)

   name    age   Monthly salary
0  sneha     16          400040
1  angel     17          290600
2   riya     18           34829

In [34]:
df

   name    age   Monthly salary
0  sneha     16          400040
1  angel     17          290600
2   riya     18           34829

In [35]:
df.info

<bound method DataFrame.info of    name    age   Monthly salary
0  sneha     16          400040
1  angel     17          290600
2   riya     18           34829>

In [36]:
df.describe()

        age   Monthly salary
count    3.0        3.000000
mean    17.0   241823.000000
std      1.0   187427.760556
min     16.0    34829.000000
25%     16.5   162714.500000
50%     17.0   290600.000000
75%     17.5   345320.000000
max     18.0   400040.000000

In [39]:
## create , save and load file
df.to_csv("test_data.csv" , index=False)

In [41]:
load_df=pd.read_csv("test_data.csv")
load_df
pd.read_csv("test_data.csv")

   name    age   Monthly salary
0  sneha     16          400040
1  angel     17          290600
2   riya     18           34829